DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 8
  TEST:
    BATCH_SIZE: 8
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5
  VISION_MAX_EPOCH: 50
  TEXT_MAX_EPOCH: 10
  NAME: adamw
  VISION_LR: 0.004
  TEXT_LR: 0.004

TRAIN:
  PRINT_FREQ: 5

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"
  VPT_LLM:
    DROPOUT: 0.0
    DEEP: True
    U1: 10.0
    U2: 2.5
    U3: 1.5
    ALPHA: 0.4
    V2T_ALTERNATING_EPOCHS: 5
    T2V_ALTERNATING_EPOCHS: 1
    STARTING_PHASE: "train_vision"
    USE_GPA: True
    GPA_MEAN: 0.9
    GPA_STD: 0.2
    MAX_LEN_QUANTILE: 1.0
    POOLING:
      NORM: "normto1"